export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"

export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST"
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS"
export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE"

export const ADD_NEWMESSAGE_REQUEST = "ADD_NEWMESSAGE_REQUEST"
export const ADD_NEWMESSAGE_SUCCESS = "ADD_NEWMESSAGE_SUCCESS"
export const ADD_NEWMESSAGE_FAILURE = "ADD_NEWMESSAGE_FAILURE"

export const REMOVE_CONTACT_REQUEST = "REMOVE_CONTACT_REQUEST"
export const REMOVE_CONTACT_SUCCESS = "REMOVE_CONTACT_SUCCESS"
export const REMOVE_CONTACT_FAILURE = "REMOVE_CONTACT_FAILURE"

export const NEWMESSAGE_RECEIVED_REQUEST = "NEWMESSAGE_RECEIVED_REQUEST"
export const NEWMESSAGE_RECEIVED_FAILURE = "NEWMESSAGE_RECEIVED_FAILURE"
export const NEWMESSAGE_RECEIVED_SUCCESS = "NEWMESSAGE_RECEIVED_SUCCESS"

export const LOGOUT ="LOGOUT"
